[package]
name = "path_redirect"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
fs-err = "3.2.2"
junction = "1.4.1"

[profile.release]
opt-level = "z"
strip = true
lto = true
panic = "abort"
codegen-units = 1

[lints.clippy]
all = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
